type Dog{
    dogId: ID
    name: String
    age: Int
    gender: String
    imageURL: String
    instagram: String
    city: String
    owner: Person
}

input DogInput{
    name: String
    age: Int
    gender: String
    instagram: String
    city: String
    file: Upload
}

type Person{
    personId: ID
    name: String
    age: Int
    gender: String
    email: String
    phone: String
}

input PersonInput{
    name: String
    age: Int
    gender: String
    email: String
    phone: String
}

type Query{
    findAllDogs: [Dog]!
    findDogByID(id: ID): Dog!
}

type Mutation{
    createDog(dogInput: [DogInput], personInput: PersonInput): [Dog]
    updateDog(id: ID, dogInput: DogInput): Dog
    deleteDog(id: ID): Boolean
    createPerson(personInput: PersonInput): Person
    updatePerson(id: ID, personInput: PersonInput): Person
}
