type Dog{
    dogId: ID
    name: String
    age: Int
    gender: String
    imageURL: String
    instagram: String
    city: String
    apodo: String
    token: String
    owner: Person
}

input DogInput{
    name: String
    age: Int
    gender: String
    instagram: String
    city: String
    apodo: String
    file: Upload
}

type Person{
    personId: ID
    name: String
    age: Int
    email: String
    phone: String
}

input PersonInput{
    name: String
    age: Int
    email: String
    phone: String
}

type DogPage{
    content: [Dog]!
    totalElements: Int
    totalPages: Int
    currentPage: Int
    hasNext: Boolean
}

type Query{
    findAllDogs(page: Int, size: Int): DogPage!
    findDogByID(id: ID): Dog!
}

type Mutation{
    createDog(dogInput: [DogInput], personInput: PersonInput): [Dog]
    updateDog(id: ID, dogInput: DogInput, token: String): Dog
    deleteDog(id: ID, token: String): Boolean
    createPerson(personInput: PersonInput): Person
    updatePerson(id: ID, personInput: PersonInput): Person
}
