spring.application.name=meeting_golden
spring.graphql.graphiql.enabled=true

# File size values
spring.servlet.multipart.max-file-size=256MB
spring.servlet.multipart.max-request-size=256MB
spring.servlet.multipart.enabled=true

spring.datasource.url=jdbc:mysql://127.0.0.1/golden_db?allowPublicKeyRetrieval=true&useSSL=False
spring.datasource.username=root
spring.datasource.password=golden
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# GCP Cloud Storage
gcs.project.id=your-gcp-project-id
gcs.bucket.name=your-gcs-bucket-name
gcs.credentials.path=/path/to/service-account-key.json


